/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { generalReadRootGet } from "../funcs/generalReadRootGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class General extends ClientSDK {
  /**
   * Read Root
   *
   * @remarks
   * Root endpoint, returns a friendly greeting.
   */
  async readRootGet(
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(generalReadRootGet(
      this,
      options,
    ));
  }
}
