workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Holiday Destinations API with Readme docs:
        inputs:
            - location: registry.speakeasyapi.dev/ritza-rzx/ritza/holiday-destinations-api-with-readme-docs
        registry:
            location: registry.speakeasyapi.dev/ritza-rzx/ritza/holiday-destinations-api-with-readme-docs
targets:
    holiday-with-readme:
        target: typescript
        source: Holiday Destinations API with Readme docs
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ritza-rzx/ritza/holiday-destinations-api-with-readme-docs-typescript-code-samples
            style: readme
            langOverride: javascript
            blocking: false
